/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ia;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import jess.Fact;
import jess.JessException;
import jess.Rete;
/**
 *
 * @author Sixto Castro
 */
public class PantallaActExtracurricular extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Act_Extracurricular
     */
    private List<JCheckBox> checkboxes = new ArrayList<JCheckBox>();
    int total;
    public PantallaActExtracurricular() {
        initComponents();
        /*pone la ventana en el Centro de la pantalla*/
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
        jButtonSgt.addActionListener(new buttonListener());
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCheckViveFuera = new javax.swing.JCheckBox();
        jCheckTrabaja = new javax.swing.JCheckBox();
        jCheckHijos = new javax.swing.JCheckBox();
        jButtonSgt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCheckCasado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jCheckImpedimento = new javax.swing.JCheckBox();
        jButtonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(180, 233, 163));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ACTIVIDADES EXTRACURRICULARES");

        jCheckViveFuera.setBackground(new java.awt.Color(180, 233, 163));
        jCheckViveFuera.setName("vivefuera"); // NOI18N
        jCheckViveFuera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckViveFueraActionPerformed(evt);
            }
        });

        jCheckTrabaja.setBackground(new java.awt.Color(180, 233, 163));
        jCheckTrabaja.setName("trabaja"); // NOI18N
        jCheckTrabaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckTrabajaActionPerformed(evt);
            }
        });

        jCheckHijos.setBackground(new java.awt.Color(180, 233, 163));
        jCheckHijos.setName("hijos"); // NOI18N
        jCheckHijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckHijosActionPerformed(evt);
            }
        });

        jButtonSgt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSgt.setText("Siguiente");
        jButtonSgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSgtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("¿Vive fuera de la ciudad?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("¿Ud trabaja?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("¿Ud es casado/a?");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("¿Tiene hijo(s)?");

        jCheckCasado.setBackground(new java.awt.Color(180, 233, 163));
        jCheckCasado.setName("casado"); // NOI18N
        jCheckCasado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckCasadoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("¿Tiene algún impedimento físico?");

        jCheckImpedimento.setBackground(new java.awt.Color(180, 233, 163));
        jCheckImpedimento.setName("impedimento"); // NOI18N
		jCheckImpedimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckImpedimentoActionPerformed(evt);
            }
        });

        jButtonAtras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAtras.setText("Atrás");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(69, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckImpedimento)))
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButtonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSgt)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckViveFuera, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckTrabaja)
                        .addComponent(jCheckCasado)
                        .addComponent(jCheckHijos))
                    .addGap(62, 62, 62)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCheckImpedimento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSgt)
                    .addComponent(jButtonAtras))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCheckViveFuera))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckTrabaja)
                        .addComponent(jLabel2))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckCasado)
                        .addComponent(jLabel3))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckHijos)
                        .addComponent(jLabel4))
                    .addContainerGap(104, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckViveFueraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckViveFueraActionPerformed
       checkboxes.add(jCheckViveFuera);
    }//GEN-LAST:event_jCheckViveFueraActionPerformed

    private void jCheckTrabajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckTrabajaActionPerformed
        // TODO add your handling code here:
       
        checkboxes.add(jCheckTrabaja);
  
    }//GEN-LAST:event_jCheckTrabajaActionPerformed

    private void jButtonSgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSgtActionPerformed
                             
        if((jCheckViveFuera.isSelected()) || (jCheckCasado.isSelected()) || (jCheckHijos.isSelected()) || (jCheckTrabaja.isSelected())
                || (jCheckImpedimento.isSelected())){
            PantallaAcademica ventanaAcademica = new PantallaAcademica();
            ventanaAcademica.setVisible(true);
            this.setVisible(false);
        }
        else{
            System.out.println("Seleccione al menos una opción para poder avanzar");
            JOptionPane.showMessageDialog(null,"Seleccione al menos una opción para poder avanzar!!", "Mensaje de Advertencia", JOptionPane.WARNING_MESSAGE); //Tipo de mensaje
        } 
    
    }//GEN-LAST:event_jButtonSgtActionPerformed

    private void jCheckCasadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckCasadoActionPerformed
        checkboxes.add(jCheckCasado);
        
    }//GEN-LAST:event_jCheckCasadoActionPerformed

    private void jCheckHijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckHijosActionPerformed
         checkboxes.add(jCheckHijos);
    }//GEN-LAST:event_jCheckHijosActionPerformed
	
	private void jCheckImpedimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckImpedimentoActionPerformed
         checkboxes.add(jCheckImpedimento);
    }//GEN-LAST:event_jCheckImpedimentoActionPerformed
	
    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        PantallaPrincipal ventanaPantallaPrincipal = new PantallaPrincipal();
        ventanaPantallaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAtrasActionPerformed
  class buttonListener implements ActionListener {
      Rete jess = new Rete();
      @Override
      public void actionPerformed(ActionEvent e) {
         for (JCheckBox checkBox : checkboxes) {
            if (checkBox.isSelected()) {
               if(checkBox.getName().equals("vivefuera")) 
                 total=total+1;
               else if(checkBox.getName().equals("trabaja")) 
                 total=total+3;
                
                else if(checkBox.getName().equals("casado")) 
                
                   total=total+1;
               
                else if(checkBox.getName().equals("hijos")) 
                
                   total=total+3;
               else if(checkBox.getName().equals("impedimento")) 
                
                   total=total+2;
            }
               
            }
         System.out.println("El peso de las actividades extracurriculares es"+ total);
          try {
              jess.batch("..//template//templates.CLP");
              jess.reset();
              String asserts = "(Actividades_Extracurriculares(Peso_ActividadesExtra "+total+"))";
              System.out.println(asserts);
              jess.assertString(asserts);
              jess.run();
              Iterator it = jess.listFacts();
                while (it.hasNext()) {
                    Fact dd = (Fact) it.next();
                    String nombre = dd.getName();
                    System.out.println(dd.toString());

                }
          } catch (JessException ex) {
                Logger.getLogger(PantallaAcademica.class.getName()).log(Level.SEVERE, null, ex);
            }
         }
} 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaActExtracurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaActExtracurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaActExtracurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaActExtracurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaActExtracurricular().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonSgt;
    public static javax.swing.JCheckBox jCheckCasado;
    public static javax.swing.JCheckBox jCheckHijos;
    public static javax.swing.JCheckBox jCheckImpedimento;
    public static javax.swing.JCheckBox jCheckTrabaja;
    public static javax.swing.JCheckBox jCheckViveFuera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
